### ISSUE TITLE
Add support for uploading attachments

### ISSUE THREAD

**Issue by jflogel** [jones2026/drone-flowdock#12]
When posting drone build messages to flowdock, it would be nice to include attachments so that files that are created during the build could be uploaded and included in flowdock messages.

**Comment by jflogel** [comment]
We were able to figure out how to add attachments via `curl` (see below) and are unsure what this would look like in `Go`.

```
curl -v -X POST -F "event=message" -F "content=my message" -H "X-flowdock-wait-for-message: true" https://api.flowdock.com/messages?flow_token=<FLOW_TOKEN>

// retrieve thread id from response and use in next cmd

curl -v -X POST -F "event=file" -F "content=@myfile.txt" -F "thread_id=<THREAD_ID>" https://api.flowdock.com/messages?flow_token=<FLOW_TOKEN>
```

**Comment by jones2026** [comment]
This is now available: https://github.com/jones2026/drone-flowdock/releases/tag/2.0.0
