### ISSUE TITLE
feature request: post to inbox

### ISSUE THREAD

**Issue by darrinholst** [jones2026/drone-flowdock#14]
It would be nice to be able to choose between posting a chat or inbox message as to not clutter up the chat with informational messages. From what I've seen the inbox is where most integrations put their messages. This is what the jenkins notifier does - https://github.com/jenkinsci/flowdock-plugin/blob/master/src/main/java/com/flowdock/jenkins/FlowdockNotifier.java#L124-L138

**Comment by jones2026** [comment]
I'll need to do some more digging to figure out how to do this. The Jenkins plugin is using the push API from what I can tell and that one is considered deprecated (https://www.flowdock.com/api/push) so I chose to not use that API for this plugin.
